# !/usr/bin/env python
# -*- coding: utf-8 -*-


class Status(object):

    HTTP_OK_BASIC = 200
    HTTP_OK_CREATED = 201
    HTTP_OK_ACCEPTED = 202
    HTTP_OK_NORESPONSE = 204
    HTTP_BAD_REQUEST = 400
    HTTP_BAD_UNAUTHORIZED = 401
    HTTP_BAD_FORBIDDEN = 403
    HTTP_BAD_NOTFOUND = 404
    HTTP_BAD_CONFLICT = 409
    HTTP_SERVICE_UNAVAILABLE = 503
    HTTP_INTERNAL_TIMEOUT = 504
